import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout for all pages.
 * @param children - The children to render.
 * @returns The root layout.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={
          (inter.className,
          "flex flex-col min-h-screen bg-linear-gradient w-full")
        }
      >
        {children}
      </body>
    </html>
  );
}
