import "./globals.css";
import React from "react";
import localfont from "next/font/local";

const inter = localfont({
  src: "../fonts/Inter.ttf",
  variable: "--font-inter",
});

const montserratAlternates = localfont({
  src: [
    {
      path: "../fonts/MontserratAlternates-Bold.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-montserrat-alternates",
});

export const metadata = {
  title: "Appollon",
  description: "Generated by create next app",
  icon: "/favicon.svg",
};

/**
 * The root layout for all pages.
 * @param children - The children to render.
 * @returns The root layout.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${montserratAlternates.variable}`}
    >
      <body className={"flex flex-col min-h-screen bg-linear-gradient w-full"}>
        {children}
      </body>
    </html>
  );
}
