name: wiki-to-pdf

on:
  gollum:
  workflow_dispatch:

jobs:
  convert-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cheackout wiki
        uses: actions/checkout@v3
        with:
          repository: 'take434/appollon.wiki'
          ref: master
          path: 'appollon.wiki'

      # - name: Install dependencies
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'
      
      # - run: find ./appollon.wiki
      # - run: npm install -g github-wikito-converter
      # - run: gwtc ./appollon.wiki -o output

      # - name: create file list
      #   id: files_list
      #   working-directory: appollon.wiki
      #   run: |
      #     echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT

      - run: ls -a
      - run: .github/bash concat-wiki.sh

      # - name: convert to pdf
      #   uses: docker://pandoc/latex:2.9
      #   with:
      #     entrypoint: /bin/sh
      #     args: -c "mkdir output;for d in */; do mkdir output/$d; done;find ./appollon.wiki -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o output/${0%.md}.pdf --pdf-engine=xelatex' {} \;find ./appollon.wiki -iname '*.png' -type f -exec cp --parents {} output/ \;find ./appollon.wiki -iname '*.svg' -type f -exec cp --parents {} output/ \;"

      - name: upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
