name: lint
on: 
  push: 

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with: 
          version: 8.4.0
      - uses: actions/setup-node@v3
        with: 
          node-version: 20.1.0
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}apps/nextjs/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs
      - run: pnpm lint
